Repository MNGFinal/CafeSync-Front, pull requests merged in 2025-02, with the labels that each got.

#11 Feature/9(메뉴조회페이지UI)
  cafe-sync/src/fran/pages/menus/Discontinue.js
  cafe-sync/src/fran/pages/menus/Menus.js
  cafe-sync/src/fran/pages/menus/Menus.module.css
  cafe-sync/src/fran/pages/menus/MenusLayout.js
  cafe-sync/src/fran/pages/menus/Regist.js
  cafe-sync/src/hq/pages/menus/HQMenus.module.css
  cafe-sync/src/hq/pages/menus/HQMenusLayout.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#12 [25.02.10] 아이디, 비밀번호 찾기 UI 구현
  cafe-sync/public/images/icons/building.png
  cafe-sync/public/images/icons/cafe.png
  cafe-sync/src/App.js
  cafe-sync/src/home/pages/find-id/CompleteId.js
  cafe-sync/src/home/pages/find-id/CompleteId.module.css
  cafe-sync/src/home/pages/find-id/FindId.js
  cafe-sync/src/home/pages/find-id/FindId.module.css
  cafe-sync/src/home/pages/find-id/FranchiseId.js
  cafe-sync/src/home/pages/find-id/FranchiseId.module.css
  cafe-sync/src/home/pages/find-id/HQId.js
  cafe-sync/src/home/pages/find-id/HQId.module.css
  cafe-sync/src/home/pages/find-pass/FindPass.js
  cafe-sync/src/home/pages/find-pass/FindPass.module.css
  cafe-sync/src/home/pages/find-pass/PassModify.js
  cafe-sync/src/home/pages/find-pass/PassModify.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#13 [25.02.10] 가맹점 메인 페이지 UI 구현
  cafe-sync/src/fran/components/Layout.js
  cafe-sync/src/fran/components/common.css
  cafe-sync/src/fran/pages/main/Main.js
  cafe-sync/src/fran/pages/main/Main.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#20 [25.02.11] 메뉴페이지UI구현
  cafe-sync/public/images/icons/poke.png
  cafe-sync/public/images/menu/iceAmericano.jpg
  cafe-sync/src/fran/pages/menus/MenuList.js
  cafe-sync/src/fran/pages/menus/MenuModal.js
  cafe-sync/src/fran/pages/menus/MenuModal.module.css
  cafe-sync/src/fran/pages/menus/Menus.js
  cafe-sync/src/fran/pages/menus/Menus.module.css
  cafe-sync/src/fran/pages/menus/MenusLayout.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#16 [25.02.11] 본사 메인 페이지 UI 구현
  cafe-sync/src/fran/components/Layout.js
  cafe-sync/src/hq/components/HQLayout.js
  cafe-sync/src/hq/components/HQcommon.css
  cafe-sync/src/hq/pages/main/HQMain.js
  cafe-sync/src/hq/pages/main/HQMain.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#22 [25.02.11] 로그인 API 구현
  cafe-sync/package-lock.json
  cafe-sync/package.json
  cafe-sync/src/App.js
  cafe-sync/src/apis/home/HomeApi.js
  cafe-sync/src/apis/home/fetchWithAuth.js
  cafe-sync/src/home/pages/login/Login.css
  cafe-sync/src/home/pages/login/Login.js
  cafe-sync/src/home/pages/protected-route/ProtectedRoute.js
  cafe-sync/src/index.js
  cafe-sync/src/redux/authSlice.js
  cafe-sync/src/redux/store.js
  cafe-sync/src/test/RegisterTest.js
Labels: ✅PR(Pull Request)✅

#23 [2025-02-11] 노트UI 구현
  cafe-sync/src/App.js
  cafe-sync/src/fran/pages/barista-note/BaristaNote.js
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/fran/pages/barista-note/NoteRegist.module.css
  cafe-sync/src/fran/pages/notice/Notice.js
  cafe-sync/src/fran/pages/notice/NoticeLayout.js
  cafe-sync/src/fran/pages/notice/NoticeRegist.js
  cafe-sync/src/fran/pages/notice/NoticeRegistLayout.js
  package-lock.json
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#32 [25.02.13] basic -> main
  cafe-sync/src/App.js
  cafe-sync/src/apis/home/HomeApi.js
  cafe-sync/src/apis/home/fetchWithAuth.js
  cafe-sync/src/fran/components/Header.js
  cafe-sync/src/fran/pages/inventory/Inventory.js
  cafe-sync/src/home/pages/login/Login.js
  cafe-sync/src/home/pages/protected-route/ProtectedRoute.js
  cafe-sync/src/hq/components/Header.js
  cafe-sync/src/redux/authSlice.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#34 [25.02.13] 메뉴 이미지 테스트용
  cafe-sync/package-lock.json
  cafe-sync/package.json
  cafe-sync/src/firebase/firebase.js
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/scripts/uploadImages.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#44 [25.02.14] 스케줄 관리 UI 구현 수정
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/FullCalendar.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️, 🛠️수정🛠️

#41 [25.02.14] 아이디 찾기 UI 구현
  cafe-sync/src/apis/home/fetchWithAuth.js
  cafe-sync/src/apis/home/findAPI.js
  cafe-sync/src/home/modal/FranchiseModal.js
  cafe-sync/src/home/modal/FranchiseModal.module.css
  cafe-sync/src/home/pages/find-id/CompleteId.js
  cafe-sync/src/home/pages/find-id/FranchiseId.js
  cafe-sync/src/home/pages/find-id/FranchiseId.module.css
  cafe-sync/src/home/pages/find-id/HQId.js
  cafe-sync/src/home/pages/find-id/HQId.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#46 [25.02.14] 메뉴 전체조회 / 검색 / 상세
  cafe-sync/src/fran/pages/menus/itemList/CoffeeList.js
  cafe-sync/src/fran/pages/menus/itemList/MenuList.js
  cafe-sync/src/fran/pages/menus/itemList/MenuList.module.css
  cafe-sync/src/fran/pages/menus/modal/MenuModal.js
  cafe-sync/src/fran/pages/menus/modal/MenuModal.module.css
  cafe-sync/src/fran/pages/menus/page/CategoryButtons.js
  cafe-sync/src/fran/pages/menus/page/Menus.js
  cafe-sync/src/fran/pages/menus/page/Menus.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#50 [25.02.14] 스케줄 관리 페이지 스케줄 등록 UI 구현
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
  cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#51 [25.02.14] 공통 모달 UI 구현
  cafe-sync/src/components/Modal.js
  cafe-sync/src/components/Modal.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#57 [25.02.17] 재고조회 UI 구현
  cafe-sync/src/apis/inventory/inventoryApi.js
  cafe-sync/src/fran/components/common.css
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/inventory/Inventory.js
  cafe-sync/src/fran/pages/inventory/Inventory.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#63 [25.02.17] 바리스타노트 전체 조회 UI 구현
  cafe-sync/package-lock.json
  cafe-sync/package.json
  cafe-sync/src/App.js
  cafe-sync/src/apis/brista-note/baristaNoteApi.js
  cafe-sync/src/fran/pages/barista-note/BaristaNote.js
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/fran/pages/barista-note/NoteRegist.module.css
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
  cafe-sync/src/fran/pages/notice/NoticeLayout.js
  cafe-sync/src/index.js
  cafe-sync/src/modules/NoteModule.js
  cafe-sync/src/modules/index.js
  cafe-sync/src/redux/store.js
  package-lock.json
Labels: 🖥️프론트엔드🖥️

#64 [25.02.17] Frature/54(메뉴soldout구현)
  cafe-sync/public/sold-out.png
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
  cafe-sync/src/fran/pages/menus/itemList/CoffeeList.js
  cafe-sync/src/fran/pages/menus/itemList/MenuList.module.css
  cafe-sync/src/fran/pages/menus/itemList/prac.js
  cafe-sync/src/fran/pages/menus/modal/MenuModal.js
  cafe-sync/src/fran/pages/menus/modal/MenuModal.module.css
Labels: ✅PR(Pull Request)✅

#67 [25.02.18] PDF 파일 추출 기능 구현
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
  cafe-sync/src/fran/pages/inventory/Inventory.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#72 [25.02.18] 충돌 수정
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
  cafe-sync/src/fran/pages/inventory/Inventory.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#76 [25.02.17] 바리스타노트 상세 조회 구현 및 검색기능 구현
  cafe-sync/package-lock.json
  cafe-sync/package.json
  cafe-sync/src/apis/brista-note/baristaNoteApi.js
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/fran/pages/barista-note/NoteRegist.module.css
  cafe-sync/src/modules/NoteModule.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#74 [25.02.18] 재고 목록 데이터 알림창 삭제 UI구현
  cafe-sync/public/animations/alert.json
  cafe-sync/public/animations/alert2.json
  cafe-sync/src/apis/inventory/inventoryApi.js
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
  cafe-sync/src/fran/pages/inventory/Inventory.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#77 [25.02.18] basic -> main
  cafe-sync/public/animations/alert.json
  cafe-sync/public/animations/alert2.json
  cafe-sync/src/apis/inventory/inventoryApi.js
  cafe-sync/src/fran/pages/inventory/Inventory.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#78 [25.02.19] 메뉴 검색 기능 구현
  cafe-sync/src/App.js
  cafe-sync/src/fran/pages/menus/itemList/CoffeeList.js
  cafe-sync/src/fran/pages/menus/modal/MenuModal.js
  cafe-sync/src/fran/pages/menus/page/CategoryButtons.js
  cafe-sync/src/fran/pages/menus/page/Menus.js
  cafe-sync/src/fran/pages/menus/page/Menus.module.css
  cafe-sync/src/hq/pages/mgment/HQMgment.js
  cafe-sync/src/hq/pages/mgment/itemList/FranList.js
  cafe-sync/src/hq/pages/mgment/itemList/FranList.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#80 [25.02.19] 입출고 데이터 조회 및 페이징 처리
  cafe-sync/package-lock.json
  cafe-sync/package.json
  cafe-sync/src/apis/inventory/inventoryApi.js
  cafe-sync/src/fran/pages/inventory/InOut.js
  cafe-sync/src/fran/pages/inventory/InOut.module.css
  cafe-sync/src/fran/pages/inventory/Inventory.js
  cafe-sync/src/fran/pages/inventory/OutRegist.js
  cafe-sync/src/fran/pages/inventory/OutRegist.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#85 [25.02.19] 메뉴 페이지네이션 / CSS 마무리
  cafe-sync/package-lock.json
  cafe-sync/package.json
  cafe-sync/src/App.js
  cafe-sync/src/apis/brista-note/baristaNoteApi.js
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/fran/pages/barista-note/NoteRegist.module.css
  cafe-sync/src/fran/pages/menus/components/dd.html
  cafe-sync/src/fran/pages/menus/itemList/CoffeeList.js
  cafe-sync/src/fran/pages/menus/itemList/DessertList.js
  cafe-sync/src/fran/pages/menus/itemList/DrinkList.js
  cafe-sync/src/fran/pages/menus/itemList/GoodsList.js
  cafe-sync/src/fran/pages/menus/itemList/MenuList.module.css
  cafe-sync/src/fran/pages/menus/items/dd.html
  cafe-sync/src/fran/pages/menus/layout/MenusLayout.js
  cafe-sync/src/fran/pages/menus/modal/MenuModal.module.css
  cafe-sync/src/fran/pages/menus/page/CategoryButtons.js
  cafe-sync/src/fran/pages/menus/page/Menus.js
  cafe-sync/src/fran/pages/menus/page/Menus.module.css
  cafe-sync/src/modules/NoteModule.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#88 [2025-02-19] 바리스타 노트 등록기능
  cafe-sync/src/apis/brista-note/baristaNoteApi.js
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/modules/NoteModule.js
Labels: 🖥️프론트엔드🖥️

#89 [25.02.19] 출고 등록 UI 구현
  cafe-sync/public/animations/loading.json
  cafe-sync/src/apis/home/findAPI.js
  cafe-sync/src/apis/inventory/inventoryApi.js
  cafe-sync/src/fran/pages/inventory/InOut.js
  cafe-sync/src/fran/pages/inventory/OutRegist.js
  cafe-sync/src/fran/pages/inventory/OutRegist.module.css
  cafe-sync/src/fran/pages/inventory/ProductSelectModal.js
  cafe-sync/src/fran/pages/inventory/ProductSelectModal.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#91 [25.02.20] Feature/87(컴플레인페이지UI구현)
  cafe-sync/src/fran/pages/complain/Complain.js
  cafe-sync/src/fran/pages/complain/components/ComplainAdd.js
  cafe-sync/src/fran/pages/complain/components/ComplainList.js
  cafe-sync/src/fran/pages/complain/styles/Complain.module.css
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#92 [25.02.19] Feature/84(메뉴페이지네이션완료)
  cafe-sync/src/fran/pages/menus/page/CategoryButtons.js
  cafe-sync/src/fran/pages/menus/page/Menus.js
  cafe-sync/src/hq/pages/mgment/itemList/FranList.js
Labels: 📢이슈📢, 🖥️프론트엔드🖥️

#96 [25.02.20] 유효성 검사 및 입출고 승인, 취소 구현
  cafe-sync/src/apis/brista-note/baristaNoteApi.js
  cafe-sync/src/apis/inventory/inventoryApi.js
  cafe-sync/src/fran/pages/inventory/InOut.js
  cafe-sync/src/fran/pages/inventory/Inventory.js
  cafe-sync/src/fran/pages/inventory/OutRegist.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#98 [25.02.20] 입출고 상세내역 조회 UI 구현
  cafe-sync/src/fran/pages/inventory/InOut.js
  cafe-sync/src/fran/pages/inventory/InOutDetail.js
  cafe-sync/src/fran/pages/inventory/InOutDetail.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#104 [25.02.20] basic -> main
  cafe-sync/public/images/icons/document.png
  cafe-sync/src/apis/brista-note/baristaNoteApi.js
  cafe-sync/src/apis/inventory/inventoryApi.js
  cafe-sync/src/fran/pages/inventory/FranInventory.js
  cafe-sync/src/fran/pages/inventory/FranInventory.module.css
  cafe-sync/src/fran/pages/inventory/InOut.js
  cafe-sync/src/fran/pages/inventory/InOutDetail.js
  cafe-sync/src/fran/pages/inventory/InOutDetail.module.css
  cafe-sync/src/fran/pages/inventory/Inventory.js
  cafe-sync/src/fran/pages/inventory/InventoryTableHeader.js
  cafe-sync/src/fran/pages/inventory/InventoryTableHeader.module.css
  cafe-sync/src/fran/pages/inventory/OutRegist.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#106 [2025-02-20] 바리스타 노트 수정기능
  cafe-sync/src/apis/brista-note/baristaNoteApi.js
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/fran/pages/barista-note/NoteRegist.module.css
  cafe-sync/src/modules/NoteModule.js
Labels: 🖥️프론트엔드🖥️

#107 Feature/43(스케줄등록UI구현완료)
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
  cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
  cafe-sync/src/fran/pages/employee/styles/ScheduleAdd.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#111 [25.02.21] 바리스타 노트 삭제 기능
  cafe-sync/src/apis/brista-note/baristaNoteApi.js
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/modules/NoteModule.js
Labels: 🖥️프론트엔드🖥️

#112 [25.02.21] 발주관리 UI, 유효성 검사, PDF 추출 기능 구현
  cafe-sync/src/apis/inventory/inventoryApi.js
  cafe-sync/src/config/generateOrderPDF.js
  cafe-sync/src/fran/pages/inventory/Orders.js
  cafe-sync/src/fran/pages/inventory/Orders.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#122 [25.02.21] 발주 내역 삭제 기능 구현
  cafe-sync/src/apis/inventory/inventoryApi.js
  cafe-sync/src/fran/pages/inventory/InOut.js
  cafe-sync/src/fran/pages/inventory/InOut.module.css
  cafe-sync/src/fran/pages/inventory/Orders.js
  cafe-sync/src/fran/pages/inventory/Orders.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#120 [25.02.21] 스케줄 조회 및 등록 로직 수정
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
  cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
Labels: ✅PR(Pull Request)✅, 🐞버그🐞, 🖥️프론트엔드🖥️, 🛠️수정🛠️

#130 [25.02.22] 전표 조회
  cafe-sync/src/apis/slip/slipApi.js
  cafe-sync/src/fran/pages/slip/Slip.js
  cafe-sync/src/fran/pages/slip/Slip.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#131 [25.02.23] 전표 추가 및 저장 구현
  cafe-sync/src/apis/slip/slipApi.js
  cafe-sync/src/fran/pages/slip/Slip.js
  cafe-sync/src/fran/pages/slip/Slip.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#132 [25.02.23] 전표 필드값 유효성 검사 추가
  cafe-sync/src/fran/pages/slip/Slip.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#133 [25.02.23] 전표 삭제 구현
  cafe-sync/src/apis/slip/slipApi.js
  cafe-sync/src/fran/pages/slip/Slip.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#134 [25.02.23] 세금 및 손익 계산서 생성 구현
  cafe-sync/src/apis/slip/slipApi.js
  cafe-sync/src/fran/pages/slip/Slip.js
  cafe-sync/src/fran/pages/slip/Slip.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#140 [25.02.24] 바리스타 노트 조회수 기능 추가
  cafe-sync/src/apis/slip/slipApi.js
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/fran/pages/slip/Slip.js
  cafe-sync/src/fran/pages/slip/Slip.module.css
Labels: 🖥️프론트엔드🖥️

#141 [25.02.24] 가맹점 상세페이지
  cafe-sync/src/apis/mgment/mgmentApi.js
  cafe-sync/src/components/ModalButton.module.css
  cafe-sync/src/hq/pages/mgment/HQMgment.js
  cafe-sync/src/hq/pages/mgment/itemList/FranList.module.css
  cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js
Labels: 🖥️프론트엔드🖥️

#149 [25.02.24] 스케줄 등록 중복(유효성) 검사
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
  cafe-sync/src/fran/pages/employee/styles/ScheduleAdd.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#159 Feature/(25.02.25)메뉴조회페이지수정
  cafe-sync/src/apis/mgment/mgmentApi.js
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
  cafe-sync/src/fran/pages/employee/styles/ScheduleAdd.module.css
  cafe-sync/src/fran/pages/menus/itemList/CoffeeList.js
  cafe-sync/src/fran/pages/menus/modal/MenuModal.js
  cafe-sync/src/fran/pages/menus/page/Menus.js
  cafe-sync/src/hq/pages/mgment/HQMgment.js
  cafe-sync/src/hq/pages/mgment/itemList/FranList.js
  cafe-sync/src/hq/pages/mgment/itemList/FranList.module.css
  cafe-sync/src/hq/pages/mgment/itemList/FranModify.js
  cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js
  cafe-sync/src/hq/pages/mgment/itemList/FranRegist.module.css
Labels: 🖥️프론트엔드🖥️

#167 [25.02.25] 스케줄 관리 수정
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleModify.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#175 [25.02.26] 가맹점 수정기능
  cafe-sync/src/apis/mgment/mgmentApi.js
  cafe-sync/src/fran/pages/menus/page/Menus.js
  cafe-sync/src/hq/pages/mgment/HQMgment.js
  cafe-sync/src/hq/pages/mgment/itemList/FranModify.js
  cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js
Labels: 🖥️프론트엔드🖥️

#182 [25.02.27] 본사 메뉴 전체 조회
  cafe-sync/src/App.js
  cafe-sync/src/apis/menus/menusApi.js
  cafe-sync/src/hq/pages/menus/HQCategoryButtons.js
  cafe-sync/src/hq/pages/menus/HQCoffeeList.js
  cafe-sync/src/hq/pages/menus/HQMenuModal.js
  cafe-sync/src/hq/pages/menus/HQMenus.js
  cafe-sync/src/hq/pages/mgment/HQMgment.js
  cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#183 [25.02.27] 스케줄 삭제 및 조회 버그 수정
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
  cafe-sync/src/fran/pages/employee/components/ScheduleModify.js
Labels: ✅PR(Pull Request)✅, 🐞버그🐞, 🖥️프론트엔드🖥️, 🛠️수정🛠️

#185 [25.02.27] 공지사항 수정 / 삭제 / 페이지네이션처리
  cafe-sync/src/apis/notice/noticeApi.js
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/fran/pages/barista-note/NoteRegist.module.css
  cafe-sync/src/fran/pages/notice/NoticeDetailLayout.js
  cafe-sync/src/fran/pages/notice/NoticeLayout.js
  cafe-sync/src/modules/NoticeModule.js
Labels: 🖥️프론트엔드🖥️

#197 [25.02.28] 본사 메뉴 수정
  cafe-sync/src/App.js
  cafe-sync/src/apis/menus/menusApi.js
  cafe-sync/src/fran/pages/menus/modal/MenuModal.module.css
  cafe-sync/src/hq/pages/menus/HQCategoryButtons.js
  cafe-sync/src/hq/pages/menus/HQCoffeeList.js
  cafe-sync/src/hq/pages/menus/HQMenuModal.js
  cafe-sync/src/hq/pages/menus/HQMenuModal.module.css
  cafe-sync/src/hq/pages/menus/HQMenus.js
  cafe-sync/src/hq/pages/mgment/HQMgment.js
  cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js
Labels: ✅PR(Pull Request)✅

#203 [25.02.28] 본사 메뉴 등록
  cafe-sync/src/hq/pages/menus/HQMenuModal.js
Labels: 🖥️프론트엔드🖥️

#202 [25.02.28] 공지사항 SModal 적용
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/fran/pages/notice/NoticeDetailLayout.js
  cafe-sync/src/fran/pages/notice/NoticeRegistLayout.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️
