Repository MNGFinal/CafeSync-Front, pull requests merged in 2025-03, with the labels that each got.

#205 [25.02.28] 컴플레인 조회 로직
  cafe-sync/src/fran/pages/complain/Complain.js
  cafe-sync/src/fran/pages/complain/components/ComplainDetail.js
  cafe-sync/src/fran/pages/complain/components/ComplainList.js
  cafe-sync/src/fran/pages/complain/styles/Complain.module.css
  cafe-sync/src/fran/pages/employee/components/ScheduleModify.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#206 [25.03.02] 채팅 기능 구현
  cafe-sync/package-lock.json
  cafe-sync/package.json
  cafe-sync/public/images/icons/default.png
  cafe-sync/src/apis/chat/chatApi.js
  cafe-sync/src/fran/components/Header.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/fran/pages/chat/Chat.js
  cafe-sync/src/fran/pages/chat/Chat.module.css
  cafe-sync/src/fran/pages/chat/Chatting.js
  cafe-sync/src/fran/pages/chat/Chatting.module.css
  cafe-sync/src/fran/pages/chat/CreateChatRoom.js
  cafe-sync/src/fran/pages/chat/CreateChatRoom.module.css
  cafe-sync/src/fran/pages/chat/Employee.js
  cafe-sync/src/fran/pages/chat/Employee.module.css
  cafe-sync/src/fran/pages/chat/Room.js
  cafe-sync/src/fran/pages/chat/Room.module.css
  cafe-sync/src/hq/components/Header.js
  cafe-sync/src/index.js
  cafe-sync/src/redux/ChatSocketProvider.js
  cafe-sync/src/redux/chatSlice.js
  cafe-sync/src/redux/store.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#207 [25.03.04] basic -> main
  cafe-sync/package-lock.json
  cafe-sync/package.json
  cafe-sync/public/images/icons/default.png
  cafe-sync/src/apis/chat/chatApi.js
  cafe-sync/src/fran/components/Header.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/fran/pages/chat/Chat.js
  cafe-sync/src/fran/pages/chat/Chat.module.css
  cafe-sync/src/fran/pages/chat/Chatting.js
  cafe-sync/src/fran/pages/chat/Chatting.module.css
  cafe-sync/src/fran/pages/chat/CreateChatRoom.js
  cafe-sync/src/fran/pages/chat/CreateChatRoom.module.css
  cafe-sync/src/fran/pages/chat/Employee.js
  cafe-sync/src/fran/pages/chat/Employee.module.css
  cafe-sync/src/fran/pages/chat/Room.js
  cafe-sync/src/fran/pages/chat/Room.module.css
  cafe-sync/src/fran/pages/complain/Complain.js
  cafe-sync/src/fran/pages/complain/components/ComplainDetail.js
  cafe-sync/src/fran/pages/complain/components/ComplainList.js
  cafe-sync/src/fran/pages/complain/styles/Complain.module.css
  cafe-sync/src/fran/pages/employee/components/ScheduleModify.js
  cafe-sync/src/hq/components/Header.js
  cafe-sync/src/index.js
  cafe-sync/src/redux/ChatSocketProvider.js
  cafe-sync/src/redux/chatSlice.js
  cafe-sync/src/redux/store.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#210 [25.03.04] 공급업체 관리
  cafe-sync/package-lock.json
  cafe-sync/public/index.html
  cafe-sync/src/apis/inventory/vendorApi.js
  cafe-sync/src/firebase/firebase.js
  cafe-sync/src/firebase/uploadImageToFirebase.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/hq/pages/inventory/HQVendor.js
  cafe-sync/src/hq/pages/inventory/HQVendor.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#215 [25.03.05] 본사 메뉴 관리(수정, 단종 기능 추가)
  cafe-sync/src/App.js
  cafe-sync/src/firebase/uploadMenuImageToFirebase.js
  cafe-sync/src/fran/pages/menus/itemList/MenuList.module.css
  cafe-sync/src/fran/pages/menus/page/Menus.js
  cafe-sync/src/fran/pages/menus/page/Menus.module.css
  cafe-sync/src/hq/components/Sidebar.js
  cafe-sync/src/hq/pages/menus/HQCategoryButtons.js
  cafe-sync/src/hq/pages/menus/HQDiscontinue.js
  cafe-sync/src/hq/pages/menus/HQDiscontinueList.js
  cafe-sync/src/hq/pages/menus/HQLayout.js
  cafe-sync/src/hq/pages/menus/HQMenuModal.js
  cafe-sync/src/hq/pages/menus/HQMenuModal.module.css
  cafe-sync/src/hq/pages/menus/HQMenus.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#212 [25.03.04] 공지사항 / 바리스타노트 SMODAL , 시간형태처리
  cafe-sync/package-lock.json
  cafe-sync/public/index.html
  cafe-sync/src/apis/inventory/vendorApi.js
  cafe-sync/src/firebase/firebase.js
  cafe-sync/src/firebase/uploadImageToFirebase.js
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/fran/pages/notice/NoticeDetailLayout.js
  cafe-sync/src/fran/pages/notice/NoticeLayout.js
  cafe-sync/src/fran/pages/notice/NoticeRegistLayout.js
  cafe-sync/src/hq/pages/barista-note/HQBaristaNote.js
  cafe-sync/src/hq/pages/inventory/HQVendor.js
  cafe-sync/src/hq/pages/inventory/HQVendor.module.css
  cafe-sync/src/hq/pages/notice/HQNotice.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#218 [25.03.05] 본사 가맹점 관리 수정 및 등록 로직 수정, UI 변경
  cafe-sync/src/apis/mgment/mgmentApi.js
  cafe-sync/src/firebase/uploadFranImageToFirebase.js
  cafe-sync/src/fran/pages/menus/page/CategoryButtons.js
  cafe-sync/src/fran/pages/menus/page/Menus.js
  cafe-sync/src/hq/pages/menus/HQCategoryButtons.js
  cafe-sync/src/hq/pages/menus/HQMenus.js
  cafe-sync/src/hq/pages/mgment/HQMgment.js
  cafe-sync/src/hq/pages/mgment/itemList/EmpSearchModal.js
  cafe-sync/src/hq/pages/mgment/itemList/EmpSearchModal.module.css
  cafe-sync/src/hq/pages/mgment/itemList/FranList.module.css
  cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js
  cafe-sync/src/hq/pages/mgment/itemList/FranRegist.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#220 [25.03.05] 컴플레인 등록 로직
  cafe-sync/package-lock.json
  cafe-sync/src/fran/pages/complain/Complain.js
  cafe-sync/src/fran/pages/complain/components/ComplainAdd.js
  cafe-sync/src/fran/pages/complain/components/ComplainList.js
  cafe-sync/src/fran/pages/complain/styles/Complain.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#232 [25.03.06] 가맹점 직원관리
  cafe-sync/src/apis/employee/employeeApi.js
  cafe-sync/src/firebase/uploadProfileImageToFirebase.js
  cafe-sync/src/fran/components/Sidebar.js
  cafe-sync/src/fran/pages/employee/Employee.js
  cafe-sync/src/fran/pages/employee/Employee.module.css
  cafe-sync/src/fran/pages/employee/EmployeeDetail.js
  cafe-sync/src/fran/pages/employee/EmployeeDetail.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#231 [25.03.06] 공지사항 바리스타노트css및main.js
  cafe-sync/package-lock.json
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/fran/pages/barista-note/NoteDetail.module.css
  cafe-sync/src/fran/pages/barista-note/NoteRegist.module.css
  cafe-sync/src/fran/pages/main/Main.js
  cafe-sync/src/fran/pages/main/Main.module.css
  cafe-sync/src/fran/pages/notice/NoteRegist.module.css
  cafe-sync/src/fran/pages/notice/NoticeDetailLayout.js
  cafe-sync/src/fran/pages/notice/NoticeLayout.js
  cafe-sync/src/fran/pages/notice/NoticeRegistLayout.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#233 [25.03.06] basic -> main
  cafe-sync/src/fran/pages/complain/components/ComplainList.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#236 [25.03.06] 가맹점 메뉴별 통계
  cafe-sync/src/App.js
  cafe-sync/src/apis/mgment/mgmentApi.js
  cafe-sync/src/firebase/uploadFranImageToFirebase.js
  cafe-sync/src/firebase/uploadMenuImageToFirebase.js
  cafe-sync/src/fran/components/Sidebar.js
  cafe-sync/src/fran/pages/barista-note/Note.module.css
  cafe-sync/src/fran/pages/menus/itemList/MenuList.module.css
  cafe-sync/src/fran/pages/menus/page/CategoryButtons.js
  cafe-sync/src/fran/pages/menus/page/Menus.js
  cafe-sync/src/fran/pages/menus/page/Menus.module.css
  cafe-sync/src/fran/pages/stats/BarChart.js
  cafe-sync/src/fran/pages/stats/MenuStats.js
  cafe-sync/src/fran/pages/stats/MenuStats.module.css
  cafe-sync/src/fran/pages/stats/Stats.js
  cafe-sync/src/fran/pages/stats/Stats.module.css
  cafe-sync/src/hq/components/Sidebar.js
  cafe-sync/src/hq/pages/menus/HQCategoryButtons.js
  cafe-sync/src/hq/pages/menus/HQDiscontinue.js
  cafe-sync/src/hq/pages/menus/HQDiscontinueList.js
  cafe-sync/src/hq/pages/menus/HQLayout.js
  cafe-sync/src/hq/pages/menus/HQMenuModal.js
  cafe-sync/src/hq/pages/menus/HQMenuModal.module.css
  cafe-sync/src/hq/pages/menus/HQMenus.js
  cafe-sync/src/hq/pages/mgment/HQMgment.js
  cafe-sync/src/hq/pages/mgment/itemList/EmpSearchModal.js
  cafe-sync/src/hq/pages/mgment/itemList/EmpSearchModal.module.css
  cafe-sync/src/hq/pages/mgment/itemList/FranList.module.css
  cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js
  cafe-sync/src/hq/pages/mgment/itemList/FranRegist.module.css
Labels: ✅PR(Pull Request)✅

#234 [25.03.05] 컴플레인 상세 조회 구현
  cafe-sync/src/fran/pages/complain/components/ComplainDetail.js
  cafe-sync/src/fran/pages/complain/components/ComplainList.js
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#239 [25.03.06] 컴플레인 페이징 처리
  cafe-sync/src/fran/pages/complain/components/ComplainList.js
  cafe-sync/src/fran/pages/complain/styles/Complain.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#244 [25.03.07] basic -> main
  cafe-sync/src/fran/pages/complain/components/ComplainList.js
  cafe-sync/src/fran/pages/complain/styles/Complain.module.css
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
  cafe-sync/src/fran/pages/main/Main.js
  cafe-sync/src/fran/pages/main/Main.module.css
  cafe-sync/src/fran/pages/main/components/ScheduleCalendar.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#246 [25.03.07] 메인화면 데이터 표현하기
  cafe-sync/src/apis/notice/noticeApi.js
  cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
  cafe-sync/src/fran/pages/main/Main.js
  cafe-sync/src/fran/pages/main/Main.module.css
  cafe-sync/src/fran/pages/main/components/DailySalesChart.js
  cafe-sync/src/fran/pages/main/components/DailySalesChart.module.css
  cafe-sync/src/fran/pages/main/components/InventoryShortageList.js
  cafe-sync/src/fran/pages/main/components/InventoryShortageList.module.css
  cafe-sync/src/fran/pages/main/components/NoticeList.js
  cafe-sync/src/fran/pages/main/components/NoticeList.module.css
  cafe-sync/src/fran/pages/main/components/SalesBarGraph.js
  cafe-sync/src/fran/pages/stats/MenuStats.module.css
  cafe-sync/src/hq/pages/notice/HQNoticeRegistLayout.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#256 [25.03.07] 본사 가맹점 관리 추가
  cafe-sync/src/hq/pages/inventory/HQFranInventory.js
  cafe-sync/src/hq/pages/inventory/HQFranInventory.module.css
  cafe-sync/src/hq/pages/inventory/HQInventoryTableHeader.js
  cafe-sync/src/hq/pages/inventory/HQInventoryTableHeader.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#253 [25.03.07] 일정 관리 UI 구현
  cafe-sync/src/hq/pages/plan/HQPlan.js
  cafe-sync/src/hq/pages/plan/PlanCalendar.js
  cafe-sync/src/hq/pages/plan/styles/Plan.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#259 [25.03.07] Basic -> Main
  cafe-sync/src/hq/pages/plan/HQPlan.js
  cafe-sync/src/hq/pages/plan/PlanCalendar.js
  cafe-sync/src/hq/pages/plan/styles/Plan.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#263 [25.03.08] 본사 세금, 손익 계산서 추가
  cafe-sync/src/fran/pages/slip/Duty.js
  cafe-sync/src/hq/pages/slip/HQDuty.js
  cafe-sync/src/hq/pages/slip/HQDuty.module.css
  cafe-sync/src/hq/pages/slip/HQIncome.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#261 [25.03.07] 일정 관리 조회 로직
  cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
  cafe-sync/src/hq/pages/plan/PlanCalendar.js
  cafe-sync/src/hq/pages/plan/styles/Plan.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#264 [25.03.08] Basic -> Main
  cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
  cafe-sync/src/hq/pages/plan/PlanCalendar.js
  cafe-sync/src/hq/pages/plan/styles/Plan.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#265 [25.03.08] 본사 손익 계산서 추가
  cafe-sync/src/hq/pages/slip/HQIncome.js
  cafe-sync/src/hq/pages/slip/HQIncome.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#267 [25.03.08] 본사 채팅 기능 추가
  cafe-sync/src/hq/pages/chat/HQChat.js
  cafe-sync/src/hq/pages/chat/HQChat.module.css
  cafe-sync/src/hq/pages/chat/HQChatting.js
  cafe-sync/src/hq/pages/chat/HQChatting.module.css
  cafe-sync/src/hq/pages/chat/HQCreateChatRoom.js
  cafe-sync/src/hq/pages/chat/HQCreateChatRoom.module.css
  cafe-sync/src/hq/pages/chat/HQEmployee.js
  cafe-sync/src/hq/pages/chat/HQEmployee.module.css
  cafe-sync/src/hq/pages/chat/HQRoom.js
  cafe-sync/src/hq/pages/chat/HQRoom.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#269 [25.03.08] 본사 발주내역 승인 반려 추가
  cafe-sync/src/apis/inventory/inventoryApi.js
  cafe-sync/src/fran/pages/inventory/Inventory.js
  cafe-sync/src/fran/pages/inventory/Orders.js
  cafe-sync/src/hq/pages/inventory/HQOrders.js
  cafe-sync/src/hq/pages/inventory/HQOrders.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#272 [25.03.08] 토큰 연장 및 만료 시 자동 로그아웃 기능 추가
  cafe-sync/src/apis/home/HomeApi.js
  cafe-sync/src/apis/home/fetchWithAuth.js
  cafe-sync/src/fran/components/Header.js
  cafe-sync/src/fran/components/common.css
  cafe-sync/src/fran/pages/employee/EmployeeDetail.js
  cafe-sync/src/hq/components/Header.js
  cafe-sync/src/redux/authSlice.js
  cafe-sync/src/redux/store.js
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#276 [25.03.11] 본사통계추가
  cafe-sync/src/hq/pages/stats/HQStats.js
  cafe-sync/src/hq/pages/stats/MenuSalesChart.js
  cafe-sync/src/hq/pages/stats/MonthlySalesChart.js
  cafe-sync/src/hq/pages/stats/StatChart.js
  cafe-sync/src/hq/pages/stats/StoreSales.js
  cafe-sync/src/hq/pages/stats/menuSalseChart.js
  cafe-sync/src/hq/pages/stats/stat.css
  cafe-sync/src/hq/pages/stats/stat.module.css
  cafe-sync/src/hq/pages/stats/todaySalesChart.js
Labels: ✅PR(Pull Request)✅

#285 [25.03.12] 일정 CSS 조정
  cafe-sync/src/fran/pages/complain/components/ComplainDetail.js
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleModify.js
  cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
  cafe-sync/src/hq/pages/plan/AddPlan.js
  cafe-sync/src/hq/pages/plan/DetailPlan.js
  cafe-sync/src/hq/pages/plan/ModifyPlan.js
  cafe-sync/src/hq/pages/plan/PlanCalendar.js
  cafe-sync/src/hq/pages/plan/styles/Plan.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️, 🛠️수정🛠️

#283 [25.03.12] 일정 등록, 수정, 삭제
  cafe-sync/src/fran/pages/complain/components/ComplainDetail.js
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleModify.js
  cafe-sync/src/hq/pages/plan/AddPlan.js
  cafe-sync/src/hq/pages/plan/DetailPlan.js
  cafe-sync/src/hq/pages/plan/ModifyPlan.js
  cafe-sync/src/hq/pages/plan/PlanCalendar.js
  cafe-sync/src/hq/pages/plan/styles/Plan.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#288 [25.03.12] 세금계산서 css 수정
  cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/fran/pages/inventory/FranInventory.module.css
  cafe-sync/src/fran/pages/slip/Duty.module.css
  cafe-sync/src/hq/pages/barista-note/BaristaNoteLayout.js
  cafe-sync/src/hq/pages/inventory/HQFranInventory.module.css
Labels: ✅PR(Pull Request)✅, 🖥️프론트엔드🖥️

#291 [25.03.13] 배포 테스트
  cafe-sync/src/apis/brista-note/baristaNoteApi.js
  cafe-sync/src/apis/chat/chatApi.js
  cafe-sync/src/apis/employee/employeeApi.js
  cafe-sync/src/apis/home/HomeApi.js
  cafe-sync/src/apis/home/fetchWithAuth.js
  cafe-sync/src/apis/home/findAPI.js
  cafe-sync/src/apis/inventory/inventoryApi.js
  cafe-sync/src/apis/inventory/vendorApi.js
  cafe-sync/src/apis/menus/menusApi.js
  cafe-sync/src/apis/mgment/mgmentApi.js
  cafe-sync/src/apis/notice/noticeApi.js
  cafe-sync/src/apis/slip/slipApi.js
  cafe-sync/src/firebase/uploadFileToFirebase.js
  cafe-sync/src/fran/components/Header.js
  cafe-sync/src/fran/pages/chat/Chatting.js
  cafe-sync/src/fran/pages/chat/Room.js
  cafe-sync/src/fran/pages/complain/components/ComplainAdd.js
  cafe-sync/src/fran/pages/complain/components/ComplainList.js
  cafe-sync/src/fran/pages/employee/Employee.js
  cafe-sync/src/fran/pages/employee/components/FullCalendar.js
  cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
  cafe-sync/src/fran/pages/employee/components/ScheduleModify.js
  cafe-sync/src/fran/pages/employee/hooks/useFetchWorkers.js
  cafe-sync/src/fran/pages/main/components/DailySalesChart.js
  cafe-sync/src/fran/pages/main/components/ScheduleCalendar.js
  cafe-sync/src/fran/pages/menus/modal/MenuModal.js
  cafe-sync/src/fran/pages/menus/page/Menus.js
  cafe-sync/src/fran/pages/stats/MenuStats.js
  cafe-sync/src/fran/pages/stats/Stats.js
  cafe-sync/src/hq/components/Header.js
  cafe-sync/src/hq/pages/chat/HQChatting.js
  cafe-sync/src/hq/pages/chat/HQRoom.js
  cafe-sync/src/hq/pages/main/components/HQDailySalesChart.js
  cafe-sync/src/hq/pages/main/components/HQPromotion.js
  cafe-sync/src/hq/pages/menus/HQDiscontinue.js
  cafe-sync/src/hq/pages/menus/HQLayout.js
  cafe-sync/src/hq/pages/menus/HQMenuModal.js
  cafe-sync/src/hq/pages/menus/HQMenus.js
  cafe-sync/src/hq/pages/mgment/itemList/EmpSearchModal.js
  cafe-sync/src/hq/pages/plan/AddPlan.js
  cafe-sync/src/hq/pages/plan/DetailPlan.js
  cafe-sync/src/hq/pages/plan/ModifyPlan.js
  cafe-sync/src/hq/pages/plan/PlanCalendar.js
  cafe-sync/src/hq/pages/stats/MenuSalesChart.js
  cafe-sync/src/hq/pages/stats/MonthlySalesChart.js
  cafe-sync/src/hq/pages/stats/StoreSales.js
  cafe-sync/src/hq/pages/stats/TodaySalesChart2.js
  cafe-sync/src/hq/pages/stats/todaySalesChart.js
  cafe-sync/src/redux/ChatSocketProvider.js
  cafe-sync/src/test/RegisterTest.js
Labels: ✅PR(Pull Request)✅
